GET http://localhost:3000/goals


###
POST http://localhost:3000/goals
Content-Type: application/json

{
    "goal": "Prueba 1",
    "frequency": 6,
    "frequencyUnit": "Year",
    "target": 7,
    "icon": "👨‍💻",
    "id": 5,
    "count": 1000
}

###
PATCH http://localhost:3000/goals/c4f31128-8a88-450b-aa40-bfade5c3dcd7
Content-Type: application/json

{
    "target": 19
}

###
DELETE http://localhost:3000/goals/643222ec-37ea-4a68-b4b5-da6035bf1d6c