GET http://localhost:3000/goals

###
POST http://localhost:3000/goals
Content-Type: application/json

{
    "goal": "Aprender React",
    "frequency": 6,
    "frequencyUnit": "Week",
    "target": 7,
    "icon": "💘",
    "id": 5,
    "count": 1000
}

###
PATCH http://localhost:3000/goals/098ca565-30ce-4e91-9b00-84c4821f19d1
Content-Type: application/json

{
    "count": 7
}

###
DELETE http://localhost:3000/goals/098ca565-30ce-4e91-9b00-84c4821f19d1