GET http://localhost:3000/goals


###
POST http://localhost:3000/goals
Content-Type: application/json

{
    "goal": "Prueba 2",
    "frequency": 6,
    "frequencyUnit": "Year",
    "target": 7,
    "icon": "👨‍💻",
    "id": 5,
    "count": 1000
}

###
PATCH http://localhost:3000/goals/094a7265-23ab-4b89-8f76-611ae5d8cc9a
Content-Type: application/json

{
    "goal":"Aprender SQL",
    "target": 22 
}

###
DELETE http://localhost:3000/goals/dc14b81f-b255-4e21-beab-d9c7cf1b7ce0